Fix AzureDeploymentTest for the conflict exception.
"Test method Microsoft.WindowsAzure.Commands.ServiceManagement.Test.FunctionalTests.FunctionalTest.AzureDeploymentTest threw exception:
System.AggregateException: One or more errors occurred. ---> Microsoft.WindowsAzure.CloudException: ConflictError: Windows Azure is currently performing an operation on this hosted service that requires exclusive access."